[package]
name = "buzzd"
version = "0.1.0"
authors = ["Alexander KÃ¶nig <alex@lisas.de>"]
edition = "2021"

[dependencies]
scheduler = "0.1.3"
paho-mqtt = "0.11"
serde_json = "1.0.93"
rppal = "0.14.1"
ctrlc = { version = "3.2.5", features = ["termination"] }
